#import "../jianzi.typ": init

#set page(width: auto, height: auto, margin: 12pt)
#set text(font: "STKaiti", size: 48pt, lang: "zh")
#set par(leading: 0.2em)
#let jianzi = init()

// Three text lines share normal paragraph baseline alignment. The middle
// character alone is generated by JianziNote; no individual offsets are used.
九九九#linebreak()
九#jianzi("九")九#linebreak()
九九九
